services:
  - type: web
    name: alx-travel-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn alx_travel_app.alx_travel_app.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: 'fu(lwa7sgs=0uy+ga&hx9n8gz8)(%hb@iif(yd06)ks7uc&b!g'
      - key: DEBUG
        value: "False"
      - key: CELERY_BROKER_URL
        value: redis://red-d1ukho6mcj7s73ekblfg:6379

  - type: worker
    name: celery-worker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A alx_travel_app worker --loglevel=info --pool=solo
    envVars:
      - key: DJANGO_SECRET_KEY
        value: 'fu(lwa7sgs=0uy+ga&hx9n8gz8)(%hb@iif(yd06)ks7uc&b!g'
      - key: DEBUG
        value: "False"
      - key: CELERY_BROKER_URL
        value: redis://red-d1ukho6mcj7s73ekblfg:6379
